### ISSUE TITLE
Not working on chrome

### ISSUE THREAD

**Issue by haimhm** [d4be4st/progress_job#1]
it is not working on chrome 41 64-bit

**Comment by d4be4st** [comment]
I really need more information then it is not working.

**Comment by haimhm** [comment]
the job is being processed but you can't see the the div filling with the color(as the job being processed) just check it for yourself and see what i meant.
(i work on win7, BTW on firefox it worked fine)

**Comment by d4be4st** [comment]
The gem does not include anyjavascript, nor bootstrap for the progressbar. Can you see the progress on the demo site? : http://progress-job-demo.hadjic.com/ ?

**Comment by haimhm** [comment]
Of course i meant to your demo site.
this is what i see: http://i.imgur.com/1qIyxSM.jpg

**Comment by d4be4st** [comment]
That looks like a bootstrap progress bar bug with windows. Sorry, can't do anything here.
