### ISSUE TITLE
Does this work with mongoid?

### ISSUE THREAD

**Issue by simonv3** [d4be4st/progress_job#8]
from this error:

``` ruby
NoMethodError - undefined method `update_column' for #<Delayed::Backend::Mongoid::Job:0x007fdf4e926c80>:
  progress_job (0.0.4) lib/progress_job/base.rb:31:in `error'
```

I'm going to assume no

**Comment by d4be4st** [comment]
Progress job assumes you are working with ActiveRecord so no.

You are free to fork it to work with mongoid.

**Comment by simonv3** [comment]
Cool, thanks for the update @d4be4st. A fork is a little bit out of scope for us, but we got the functionality we needed inspired by this project :)
