### ISSUE TITLE
TESTING?

### ISSUE THREAD

**Issue by rruiz858** [d4be4st/progress_job#9]
I have managed to get this to work. I haven't, however, been able to successfully made my tests pass. If I make delay job not work on my test environment, then the test complains about not being able to update the stage of the progress bar....

**Comment by mschneider85** [comment]
ProgressJob::Base requires an underlying persistent job.
You could add sth like this in jobs inheriting from ProgressJob::Base:
```ruby
def update_stage_progress(stage, step: 1)
  super if @job.present?
end
